openapi: 3.0.0
info:
  title: RSA API
  description: "CRC's RSA (Rural Spectrum Analysis) application is a web service that\
    \ supports \nresearch efforts by providing an interface to generate RSA reports\
    \ and monitor RSA jobs. \n\n"
  version: 1.0.0
servers:
- url: https://1.1.1.1/rsa
tags:
- name: RSA
  description: access to RSA code
- name: server
  description: general server functionality
paths:
  /healthcheck:
    get:
      tags:
      - server
      summary: Healthcheck for Appliation Load Balancer
      description: Healtch check response for server
      operationId: healthcheck
      responses:
        "200":
          description: OK
      x-openapi-router-controller: swagger_server.controllers.server_controller
  /jobs:
    get:
      tags:
      - RSA
      summary: Gets all RSA jobs. Filtering can be used to get a filtered list of
        jobs.
      description: "Gets all job resources based on filters. Any of the input parameters\
        \ can be used as a filter. If filters are none, then all jobs will be fetched\n\
        \nThe resultUrl, when appropriate, will contain a report of the RSA job."
      operationId: get_jobs
      parameters:
      - name: id
        in: query
        description: ID of the RSA job
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: service
        in: query
        description: Service parameter of RSA job
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: status
        in: query
        description: Status of RSA job
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: name
        in: query
        description: Name of RSA job
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: block
        in: query
        description: Block parameter of RSA job
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: operator
        in: query
        description: Operator parameter of RSA job
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: service_area
        in: query
        description: Service area paramter of RSA job
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: aggregation_level
        in: query
        description: Aggregation level paramter of RSA job
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: propagation_model_type
        in: query
        description: Propagation model of RSA job
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: dataset_date
        in: query
        description: Date of RSA job
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: result_url
        in: query
        description: Result URL of RSA job
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Returns a list of jobs with the user's input filters.
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                  - $ref: '#/components/schemas/job'
                x-content-type: application/json
        "300":
          description: No jobs with the input filters were found
        "401":
          description: Unauthorized
      x-openapi-router-controller: swagger_server.controllers.rsa_controller
    post:
      tags:
      - RSA
      summary: Starts a New RSA Job
      description: "Starts a new RSA job for the given parameters and returns the\
        \ id of the newly \ncreated job.\n\nPrior to starting the job (e.g. just before\
        \ executing), the job status \nshould become `inprogress` and following the\
        \ successful completion and \nsaving of results, the job status will become\
        \ `completed`. It is \nexpected that the RSA job would be in a `pending` state\
        \ for only \nmoments.\n\nThe resultUrl, when appropriate, will contain a report\
        \ of the RSA job."
      operationId: post_job
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body'
      responses:
        "200":
          description: "Job Response\n\nContains data based on the status:\n- `pending`:\
            \ returns the id for the job, time.creation\n- `inprogress`: same as for\
            \ `pending` plus the time.start\n- `complete`: same as for `inprogress`\
            \ plus the time.end and the resultUrl\n- `failed`: same as for `inprogress`plus\
            \ the time.end and a failureMessage\n\n"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_status_200'
        "300":
          description: Invalid input
        "401":
          description: Unauthorized
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.rsa_controller
  /jobs/{job_id}:
    get:
      tags:
      - RSA
      summary: Get RSA Job Resource. Returns the status and RSA parameters of a job
      description: "Gets the job resource\n\nThe resultUrl, when appropriate, will\
        \ contain a report of the RSA job."
      operationId: get_job
      parameters:
      - name: job_id
        in: path
        description: ID of the RSA job
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Returns job resource if job if has been succesfully fetched.
          content:
            application/json:
              schema:
                type: array
                items:
                  allOf:
                  - $ref: '#/components/schemas/job'
                x-content-type: application/json
        "300":
          description: Job ID not found
        "401":
          description: Unauthorized
      x-openapi-router-controller: swagger_server.controllers.rsa_controller
    put:
      tags:
      - RSA
      summary: Stops an RSA job
      description: "Stops an RSA job, and will return success if job has been successfully\
        \ stopped."
      operationId: stop_job
      parameters:
      - name: job_id
        in: path
        description: ID of the RSA job
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: OK
        "400":
          description: Bad request
        "401":
          description: Unauthorized
      x-openapi-router-controller: swagger_server.controllers.rsa_controller
  /jobs/{job_id}/status:
    get:
      tags:
      - RSA
      summary: Get RSA Job status and status details
      description: "Gets the job status\n\nThe resultUrl, when appropriate, will contain\
        \ a report of the RSA job."
      operationId: get_job_status
      parameters:
      - name: job_id
        in: path
        description: ID of the RSA job
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Returns job status if job id has been successfully fetched.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_status_200'
        "300":
          description: Job ID not found
        "401":
          description: Unauthorized
      x-openapi-router-controller: swagger_server.controllers.rsa_controller
components:
  schemas:
    job:
      type: object
      properties:
        id:
          type: string
          description: ID of the job
        services:
          type: array
          items:
            $ref: '#/components/schemas/body_services'
        status:
          type: string
          description: The current status of the job
          enum:
          - pending
          - inprogress
          - completed
          - failed
        job_status_details:
          $ref: '#/components/schemas/job_job_status_details'
        operators:
          type: array
          description: Operators of RSA job
          items:
            type: string
        service_areas:
          type: array
          description: Service areas of RSA job
          items:
            type: string
        aggregationLevel:
          type: string
          description: Aggregation level of RSA job
        propagation_model_type:
          type: string
          description: Propagation model of RSA job
        propagation_model_params:
          type: string
          description: Parameters of propagation model
        dataset_date:
          type: string
          description: The date to be used to retrieve the datasets used for RSA analysis
          format: date
        result_url:
          type: string
          description: "Signed S3 URL containing the result of the job - only present\
            \ if \nstatus is `completed`. The URL will only be valid for 30 minutes\
            \ \nfrom the time of calling this method. See the parent method for \n\
            details on result contents."
      description: "The resource of the given job, includes status and input parameters"
    jobStatusResult:
      required:
      - id
      - status
      type: object
      properties:
        id:
          type: string
          description: Id of the job
        status:
          type: string
          description: Status of the job
        job_status_details:
          $ref: '#/components/schemas/job_job_status_details'
        result_url:
          type: string
          description: "Signed S3 URL containing the result of the job - only present\
            \ if \nstatus is `completed`. The URL will only be valid for 30 minutes\
            \ \nfrom the time of calling this method. See the parent method for \n\
            details on result contents."
      description: The status and/or result of the given job
    body:
      required:
      - name
      - propagationModel
      - serviceAreas
      type: object
      properties:
        name:
          type: string
          description: Short name or description of the job
        services:
          type: array
          items:
            $ref: '#/components/schemas/body_services'
        operators:
          type: array
          items:
            type: string
        serviceAreas:
          type: array
          items:
            type: string
        aggregationLevel:
          type: string
          enum:
          - grid
          - Tier1
          - Tier2
          - Tier3
          - Tier4
          - Tier5
        propagationModel:
          $ref: '#/components/schemas/body_propagationModel'
        datasetDate:
          type: string
          description: The date to be used to retrieve the datasets used for RSA analysis
          format: date
        resultUrl:
          type: string
          description: "Signed S3 URL containing the result of the job - only present\
            \ if \nstatus is `completed`. The URL will only be valid for 30 minutes\
            \ \nfrom the time of calling this method. See the parent method for \n\
            details on result contents."
      example:
        name: Test1
        services:
        - service: CELL
          blocks:
          - A
          - B
        - service: PCS
          blocks:
          - A
        operators:
        - BELL
        - TELUS
        serviceAreas:
        - "ON"
        - QC
        resultUrl: https://vre-rsa-api.s3.amazonaws.com/results/
        aggregationLevel: Tier4
        datasetDate: 2021-11-17
        propagationModel:
          model: fixedRadius
          parameters:
            radiusKM: 10
    inline_response_job_200:
      description: RSA job that contains its status and parameters
      allOf:
      - $ref: '#/components/schemas/job'
    inline_response_status_200:
      description: Job Result for RSA job
      allOf:
      - $ref: '#/components/schemas/jobStatusResult'
    jobResult_time:
      required:
      - creation
      type: object
      properties:
        creation:
          type: string
          description: The time at which the job was created in pending status
          format: date-time
        start:
          type: string
          description: The time at which the job entered `inprogress` status
          format: date-time
        end:
          type: string
          description: The time at which the job entered `completed` or `failed` status
          format: date-time
      description: Relevant job timestamps
    fixedRadius_prop_model_parameters:
      required:
      - radiusKM
      type: object
      properties:
        radiusKM:
          type: number
    longleyRice_prop_model_parameters:
      required:
      - climaticZone
      - confidenceLevel
      - elevDataSamplingResKm
      - elevSource
      - groundConductivity
      - groundDielectricConst
      - rxHeight
      - serviceThreshold
      - surfaceRefractivity
      - timeAvail
      type: object
      properties:
        serviceThreshold:
          type: number
        surfaceRefractivity:
          type: number
        groundDielectricConst:
          type: number
        groundConductivity:
          type: number
        climaticZone:
          type: string
        confidenceLevel:
          type: number
        timeAvail:
          type: number
        rxHeight:
          type: number
        elevDataSamplingResKm:
          type: number
        elevSource:
          type: string
    body_services:
      type: object
      properties:
        service:
          type: string
        blocks:
          type: array
          items:
            type: string
    body_propagationModel:
      required:
      - model
      - parameters
      type: object
      properties:
        model:
          type: string
          enum:
          - fixedRadius
          - longleyRice:covlib
        parameters:
          type: object
          description: Parameters that correspond to the selected algorithm.
          oneOf:
          - $ref: '#/components/schemas/fixedRadius_prop_model_parameters'
          - $ref: '#/components/schemas/longleyRice_prop_model_parameters'
    job_job_status_details:
      type: object
      properties:
        name:
          type: string
          description: Name of job
        progressMessage:
          type: string
          description: The current progress of the job
        failureMessage:
          type: string
          description: "If the job status is `failed`, this will contain the failure\
            \ message."
        time:
          $ref: '#/components/schemas/jobResult_time'
      description: Status details of job
      example: null

